name: e_commers
description: A new Flutter project.

version: 

environment:
  sdk: ">=2.12.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  



  
  cupertino_icons: 
  get: 
  google_sign_in: ^4.5.6
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"
  flutter_facebook_auth: "^1.0.0"
  

dev_dependencies:
  build_runner: 
  flutter_test:
    sdk: flutter

  
 


flutter:
  uses-material-design: true
  assets:
    - assets/images/
     

  